const prendas = [{
        id: 01,
        categoria: "cabeza",
        nombre: "Boina de la Guardia Real",
        icono: "img/iconos/boina-guardia-real.png",
        imagen: "img/boina-guardia-real.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ataque cargado +",
        obtencion: "En el Castillo de Hyrule",
        descripcion: "Forma parte del atuendo de la guardia real de Hyrule. Es más ligera de lo que parece y no dificulta en absoluto los movimientos. Es muy singular y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 02,
        categoria: "cabeza",
        nombre: "Capucha de Ravio",
        icono: "img/iconos/capucha-ravio.png",
        imagen: "img/capucha-ravio.png",
        defensa: 2,
        efecto: "Mejora la escalada",
        bonificacion: "Ninguno",
        obtencion: "En la Fuente del Valor",
        descripcion: "Capucha de un mercader ambulante cuyo brazalete permitía convertirse en pintura. Acelera los movimientos laterales al escalar. Es muy singular y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 03,
        categoria: "cabeza",
        nombre: "Capucha Hyliana",
        icono: "img/iconos/capucha-hyliana.png",
        imagen: "img/capucha-hyliana.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En la tienda de aldea Hatelia",
        descripcion: "Capucha tejida con materiales resistentes usando métodos hylianos tradicionales. Ideal para viajeros, dado que protege tanto del sol como de las inclemencias del tiempo.",
        mejoras: ["Cuerno de Bokoblin (x5) - Defensa: 5", "Cuerno de Bokoblin (x8) y Colmillo de Bokoblin (x5) - Defensa: 8", "Cuerno de Bokoblin (x10) y Víscera de Bokoblin (x5) - Defensa: 12", "Víscera de Bokoblin (x15) y Ámbar (x30) - Defensa: 20"]
    },
    {
        id: 04,
        categoria: "cabeza",
        nombre: "Capucha Zora",
        icono: "img/iconos/capucha-zora.png",
        imagen: "img/capucha-zora.png",
        defensa: 3,
        efecto: "Nadar +, Torbellino",
        bonificacion: "Resistencia nadar +",
        obtencion: "En un cofre en el lago Toto",
        descripcion: "Prenda zora elaborada con escamas de dragón que ayuda a nadar más rápido y permite ejecutar torbellinos para atacar en el agua",
        mejoras: ["Cuerno de Lizalfo (x3)- Defensa: 5", "Garra de Lizalfo (x5) y Lubina de Hyrule (x5) - Defensa: 8", "Cola de Lizalfo (x5) y Lubina vivaz (x5) - Defensa 12)", "Cola de Lizalfo (x10) y Ópalo (x15) - Defensa: 20"]
    },
    {
        id: 05,
        categoria: "cabeza",
        nombre: "Casco Aislante",
        icono: "img/iconos/casco-aislante.png",
        imagen: "img/casco-aislante.png",
        defensa: 3,
        efecto: "Resistencia a la electricidad",
        bonificacion: "Antirrayos",
        obtencion: "En la misión secundaria '¡Rayos!'",
        descripcion: "Casco resistente a la electricidad fabricado mediante técnicas ancestrales. Contiene un material aislante denominado 'caucho' que no existe a día de hoy.",
        mejoras: ["Gelatina eléctrica (x3) - Defensa 5)", "Gelatina eléctrica (x5) y Fruta electro (x5) - Defensa: 8", "Seta electro (x5) y Cola de Lizalfo eléctrico (x5) - Defensa: 12", "Cola de Lizalfo eléctrico (x10) y Topacio (x10) - Defensa: 20"]
    },
    {
        id: 06,
        categoria: "cabeza",
        nombre: "Casco Ancestral",
        icono: "img/iconos/casco-ancestral.png",
        imagen: "img/casco-ancestral.png",
        defensa: 4,
        efecto: "Resistencia ancestral",
        bonificacion: "Ataque ancestral +",
        obtencion: "En el laboratorio de Akkala",
        descripcion: "Accesorio fabricado con piezas de guardián gracias a la investigación de Rotver. Reduce el daño sufrido por ataques de energía ancestral.",
        mejoras: ["Tornillo ancestral (x5) y Resorte ancestral (x5) - Defensa: 7", "Resorte ancestral (x15) y Engranaje ancestral (x10) - Defensa: 12", "Eje ancestral (x5) y Núcleo ancestral (x5) - Defensa: 18", "Fragmento de estrella (x3) y Gran núcleo ancestral (x3) - Defensa: 28"]
    },
    {
        id: 07,
        categoria: "cabeza",
        nombre: "Casco de Bárbaro",
        icono: "img/iconos/casco-barbaro.png",
        imagen: "img/casco-barbaro.png",
        defensa: 3,
        efecto: "Ataque +",
        bonificacion: "Ataque cargado +",
        obtencion: "En el santuario de Tu Ka'loh",
        descripcion: "Un casco usado por una antigua tribu guerrera que habitaba en Farone. Se cree que el extraño diseño que lo adorna otorga fuerza y fiereza.",
        mejoras: ["Cuerno de Centaleón (x1) - Defensa: 5", "Cuerno de Centaleón (x3) y Pezuña de Centaleón (x2) - Defensa: 8", "Pezuña de Centaleón (x4)y Víscera de centaleón (x1) - Defensa: 12", "Víscera de centaleón (x2) y Cuerno de Elden (x1) - Defensa: 20"]
    },
    {
        id: 08,
        categoria: "cabeza",
        nombre: "Casco de Buceador",
        icono: "img/iconos/casco-buceador.png",
        imagen: "img/casco-buceador.png",
        defensa: 5,
        efecto: "Nadar +",
        bonificacion: "Ninguno",
        obtencion: "Gran Puente de Hylia",
        descripcion: "[Colaboración con Xenoblade Chronicles 2] Prenda imprescindible para todo aquel que quiera buscar tesoros en el mar de nubes. Es muy preciada y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 09,
        categoria: "cabeza",
        nombre: "Casco de Espectro",
        icono: "img/iconos/casco-espectro.png",
        imagen: "img/casco-espectro.png",
        defensa: 8,
        efecto: "Ataque +",
        bonificacion: "Ninguno",
        obtencion: "Gran Puente de Hylia. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Casco idéntico al que solían llevar los espectros blindados que, según la leyenda, aterrorizaban hasta al más valiente. Es muy preciado y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 10,
        categoria: "cabeza",
        nombre: "Casco de Ganon Fantasma",
        icono: "img/iconos/casco-ganon-fantasma.png",
        imagen: "img/casco-ganon-fantasma.png",
        defensa: 4,
        efecto: "Sigilo +",
        bonificacion: "Armas esqueléticas +",
        obtencion: "Cascada entre el lago Telye y el lago Faroria. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Se cuenta que este inquietante casco fue portado por una entidad maligna que el rey malvado creó a su propia semejanza. Es muy preciado y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 11,
        categoria: "cabeza",
        nombre: "Casco de Midna",
        icono: "img/iconos/casco-midna.png",
        imagen: "img/casco-midna.png",
        defensa: 7,
        efecto: "Resistencia ancestral",
        bonificacion: "Ninguno",
        obtencion: "Templo de los sabios. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Casco muy similar al que llevaba la princesa del Crepúsculo cuando luchó junto al héroe. Es muy preciado y dificil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 12,
        categoria: "cabeza",
        nombre: "Casco de Zant",
        icono: "img/iconos/casco-zant.png",
        imagen: "img/casco-zant.png",
        defensa: 3,
        efecto: "Anticongelación",
        bonificacion: "Ninguno",
        obtencion: "Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Se dice que fue portado por el despiadado rey usurpador del reino del Crepúsculo. Es muy preciado y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 13,
        categoria: "cabeza",
        nombre: "Casco del Trueno",
        icono: "img/iconos/casco-trueno.png",
        imagen: "img/casco-trueno.png",
        defensa: 3,
        efecto: "Resistencia al rayo",
        bonificacion: "Ninguno",
        obtencion: "En la misión secundaria 'El orgullo de la tribu'",
        descripcion: "Tesoro sagrado de la tribu gerudo, heredado durante generaciones. Tiene el poder de repeler los rayos, aunque solo la matriarca puede utilizarlo.",
        mejoras: "No tiene"
    },
    {
        id: 14,
        categoria: "cabeza",
        nombre: "Casco divino de Medoh",
        icono: "img/iconos/casco-medoh.png",
        imagen: "img/casco-medoh.png",
        defensa: 4,
        efecto: "Resistencia al frío. Ver puntos de salud de los enemigos",
        bonificacion: "Ataque ancestral +",
        obtencion: "Se desbloquea con el amiibo de Revali",
        descripcion: "Casco otorgado a quien ha de pilotar a Vah Medoh. Potencia las habilidades del portador.",
        mejoras: "No tiene"
    },
    {
        id: 15,
        categoria: "cabeza",
        nombre: "Casco divino de Naboris",
        icono: "img/iconos/casco-naboris.png",
        imagen: "img/casco-naboris.png",
        defensa: 4,
        efecto: "Resistencia eléctrica. Ver puntos de salud de los enemigos",
        bonificacion: "Ataque ancestral +",
        obtencion: "Se desbloquea con el amiibo de Urbosa",
        descripcion: "Casco otorgado a quien ha de pilotar a Vah Naboris. Potencia las habilidades del portador.",
        mejoras: "No tiene"
    },
    {
        id: 16,
        categoria: "cabeza",
        nombre: "Casco divino de Rudania",
        icono: "img/iconos/casco-rudania.png",
        imagen: "img/casco-rudania.png",
        defensa: 4,
        efecto: "Resistencia al fuego. Ver puntos de salud de los enemigos",
        bonificacion: "Ataque ancestral +",
        obtencion: "Se desbloquea con el amiibo de Daruk",
        descripcion: "Casco otorgado a quien ha de pilotar a Vah Rudania. Potencia las habilidades del portador.",
        mejoras: "No tiene"
    },
    {
        id: 17,
        categoria: "cabeza",
        nombre: "Casco divino de Ruta",
        icono: "img/iconos/casco-ruta.png",
        imagen: "img/casco-ruta.png",
        defensa: 4,
        efecto: "Nadar +. Ver puntos de salud de los enemigos",
        bonificacion: "Ataque ancestral +",
        obtencion: "Se desbloquea con el amiibo de Mipha",
        descripcion: "Casco otorgado a quien ha de pilotar a Vah Ruta. Potencia las habilidades del portador.",
        mejoras: "No tiene"
    },
    {
        id: 18,
        categoria: "cabeza",
        nombre: "Casco Hyliano",
        icono: "img/iconos/casco-hyliano.png",
        imagen: "img/casco-hyliano.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En la tienda de aldea Hatelia",
        descripcion: "Casco extremadamente resistente usado por los soldados que luchaban en la vanguardia. Aquellos que aún existen a día de hoy son los supervivientes del gran cataclismo.",
        mejoras: ["Gelatina de Chuchu (x5) y Víscera de Bokoblin (x3) - Defensa: 7", "Ala de Keese (x5) y Víscera de Moblin (x3) - Defensa: 12", "Cola de Lizalfo (x5) y Víscera de Hinox (x3) - Defensa: 18", "Pezuña de Centaleón (x4) y Vísceras de Centaleón (x2) - Defensa: 28"]
    },
    {
        id: 19,
        categoria: "cabeza",
        nombre: "Casco Ignífugo",
        icono: "img/iconos/casco-ignifugo.png",
        imagen: "img/casco-ignifugo.png",
        defensa: 3,
        efecto: "Resistencia al fuego",
        bonificacion: "Antillamas",
        obtencion: "En la tienda 'Magmanífico' de la Ciudad Goron",
        descripcion: "Accesorio de piedra elaborado para los turistas que visitan Ciudad Goron. Cubre toda la cabeza y es resistente a las llamas",
        mejoras: ["Lagarto ignífugo (x1) y Cuerno de Moblin (x2) - Defensa: 5", "Lagarto ignífugo (x3) y Colmillo de Moblin (x4) - Defensa: 8", "Mariposa ignífuga (x3) y Víscera de Moblin (x3) - Defensa: 12", "Mariposa ignífuga (x5) y Víscera de Hinox (x2) - Defensa: 20"]
    },
    {
        id: 20,
        categoria: "cabeza",
        nombre: "Coletero del Desierto",
        icono: "img/iconos/coletero-desierto.png",
        imagen: "img/coletero-desierto.png",
        defensa: 3,
        efecto: "Resistencia al calor",
        bonificacion: "Antielectricidad",
        obtencion: "Club Secreto Gerudo, Ciudadela Gerudo ,El toque de Kaenne, Aldea Arkadia",
        descripcion: "Accesorio masculino vendido en el Club Secreto Gerudo. Ayuda a combatir el calor, ya que los zafiros que lo adornan albergan el poder del hielo.",
        mejoras: ["Gelatina gélida (x3) - Defensa: 5", "Gelatina gélida (x5) y Ala de Keese de hielo (x3) - Defensa: 8", "Ala de Keese de hielo (x8) y Cola de Lizalfo gélido (x3) - Defensa: 12", "Cola de Lizalfo gélido (x10) y Zafiro (x5) - Defensa: 20"]
    },
    {
        id: 21,
        categoria: "cabeza",
        nombre: "Diadema de Diamante",
        icono: "img/iconos/diadema-diamante.png",
        imagen: "img/diadema-diamante.png",
        defensa: 4,
        efecto: "Resistencia ancestral",
        bonificacion: "Ninguno",
        obtencion: "La Gema del Desierto ,Isla Lomei",
        descripcion: "Accesorio gerudo de lujo adornado con un diamante que otorga el poder de la luz y reduce el daño sufrido por ataques de enemigos ancestrales.",
        mejoras: ["Diamante (x2) y Pedernal(x3) - Defensa: 7", "Diamante(x4) y Pedernal(x3) - Defensa: 12", "Diamante (x6) y Fragmento de estrella(x1) - Defensa: 18", "Diamante (x10) y Fragmento de estrella(x1) - Defensa: 28"]
    },
    {
        id: 22,
        categoria: "cabeza",
        nombre: "Diadema de Rubí",
        icono: "img/iconos/diadema-rubi.png",
        imagen: "img/diadema-rubi.png",
        defensa: 3,
        efecto: "Resistencia al frío",
        bonificacion: "Ninguno",
        obtencion: "La Gema del Desierto",
        descripcion: "Accesorio gerudo cuyo rubí alberga el poder del fuego. Otorga protección frente a las bajas temperaturas.",
        mejoras: ["Pedernal (x3) y Rubí(x2) - Defensa: 5 ", "Pedernal (x3) y Rubí (x4) - Defensa: 8 ", "Fragmento de estrella (x1) y Rubí (x6) - Defensa: 12 ", "Fragmento de estrella (x1) y Rubí (x10) - Defensa: 20"]
    },
    {
        id: 106,
        categoria: "cabeza",
        nombre: "Diadema de Zafiro",
        icono: "img/iconos/diadema-zafiro.png",
        imagen: "img/diadema-zafiro.png",
        defensa: 3,
        efecto: "Resistencia al calor	",
        bonificacion: "Ninguno",
        obtencion: "La Gema del Desierto",
        descripcion: "Delicado accesorio gerudo que ayuda a soportar temperaturas altas. Se dice que el zafiro que lo adorna alberga el poder del hielo.",
        mejoras: ["Pedernal (x3) y Zafiro (x2) - Defensa: 5 ", "Pedernal (x3) y Zafiro (x4) - Defensa: 8 ", "Fragmento de estrella (x1) y Zafiro (x6) - Defensa: 12 ", "Fragmento de estrella (x1) y Zafiro (x10) - Defensa: 20"]
    },
    {
        id: 23,
        categoria: "cabeza",
        nombre: "Gorro del Cielo",
        icono: "img/iconos/gorro-cielo.png",
        imagen: "img/gorro-cielo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Este gorro, perteneció al héroe que surcaba los cielos.",
        mejoras: ["Zafiro (x1) y Fragmento de estrella (x1) - Defensa: 5", "Zafiro (x3) y Fragmento de estrella (x3) Defensa: 8", "Zafiro (x5) y Fragmento de estrella (x3) - Defensa: 12", "Zafiro (x10) y Fragmento de estrella (x4) - Defensa: 20"]
    },
    {
        id: 24,
        categoria: "cabeza",
        nombre: "Gorro del Crepúsculo",
        icono: "img/iconos/gorro-crepusculo.png",
        imagen: "img/gorro-crepusculo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "El gorro que portaba el héroe que se enfrentó a los monstruos del Crepúsculo.",
        mejoras: ["Topacio (x1) y Fragmento de estrella (x1) - Defensa: 5", "Topacio (x3) y Fragmento de estrella (x2) - Defensa: 8", "Topacio (x5) y Fragmento de estrella (x3) - Defensa: 12", "Topacio (x10) y Fragmento de estrella(x4) - Defensa 20)"]
    },
    {
        id: 25,
        categoria: "cabeza",
        nombre: "Gorro del Héroe",
        icono: "img/iconos/gorro-heroe.png",
        imagen: "img/gorro-heroe.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "El gorro que llevaba con orgullo un héroe de leyenda.",
        mejoras: ["Rubí (x1) y Fragmento de estrella (x1) - Defensa: 5", "Rubí (x3) y Fragmento de estrella (x2) - Defensa: 8", "Rubí (x5) y Fragmento de estrella (x3) - Defensa: 12", "Rubí (x10) y Fragmento de estrella (x4) - Defensa: 20"]
    },
    {
        id: 26,
        categoria: "cabeza",
        nombre: "Gorro del Tiempo",
        icono: "img/iconos/gorro-tiempo.png",
        imagen: "img/gorro-tiempo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Este gorro perteneció al héroe que viajaba por el tiempo. Su diseño sencillo permite que lo puedan llevar tanto niños como adultos.",
        mejoras: ["Ámbar (x3) y Fragmento de estrella (x1) - Defensa: 5", "Ámbar (x5) y Fragmento de estrella (x2) - Defensa: 8", "Ámbar (x15) y Fragmento de estrella (x3) - Defensa: 12", "Ámbar (x30) y Fragmento de estrella (x4) - Defensa: 20"]
    },
    {
        id: 27,
        categoria: "cabeza",
        nombre: "Gorro del Viento",
        icono: "img/iconos/gorro-viento.png",
        imagen: "img/gorro-viento.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Gorro preferido del héroe que navegó por todo el océano con la ayuda del viento.",
        mejoras: ["Ópalo (x3) y Fragmento de estrella (x1) - Defensa: 5", "Ópalo (x5) y Fragmento de estrella (x2) - Defensa: 8", "Ópalo (x10) y Fragmento de estrella (x3) - Defensa: 12", "Ópalo (x20) y Fragmento de estrella (x4) - Defensa: 20)"]
    },
    {
        id: 28,
        categoria: "cabeza",
        nombre: "Gorro de lo Salvaje",
        icono: "img/iconos/gorro-salvaje.png",
        imagen: "img/gorro-salvaje.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "En la misión secundaria 'Un regalo para los monjes'",
        descripcion: "Gorro creado para el héroe que recorre las tierras salvajes. Curiosamente, te sienta como un guante.",
        mejoras: ["Bellota (x10) y Escama de Faren (x2) - Defensa: 7", "Miel de vigor (x5) y Garra de Faren (x2) - Defensa: 12", "Escarabajo vigoroso (x5) y Colmillo de Faren (x2) - Defensa: 18", "Fragmento de estrella (x1)y cuerno de Faren (x2) - Defensa: 28"]
    },
    {
        id: 29,
        categoria: "cabeza",
        nombre: "Gorro de Tingle",
        icono: "img/iconos/gorro-salvaje.png",
        imagen: "img/gorro-salvaje.png",
        defensa: 2,
        efecto: "Ninguno",
        bonificacion: "Velocidad nocturna +",
        obtencion: "Mercado central. Disponible con el DLC 'Las Pruebas Legendarias'",
        descripcion: "Gorro similar al de un individuo que afirmaba ser la rencarnación de un hada. Kurulin. Es muy difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 30,
        categoria: "cabeza",
        nombre: "Máscara de Bokoblin",
        icono: "img/iconos/mascara-bokoblin.png",
        imagen: "img/mascara-bokoblin.png",
        defensa: 3,
        efecto: "Incógnito con Bokoblin",
        bonificacion: "Ninguno",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Una máscara hecha a mano por Kilton que tiene un punto adorable. A los Bokoblin les cuesta más detectar a su portador.",
        mejoras: "No tiene"
    },
    {
        id: 31,
        categoria: "cabeza",
        nombre: "Máscara de Centaleón",
        icono: "img/iconos/mascara-centaleon.png",
        imagen: "img/mascara-centaleon.png",
        defensa: 3,
        efecto: "Incógnito con Centaleón",
        bonificacion: "Ninguno",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Una máscara hecha a mano por Kilton. Está tan bien elaborada que hasta parece real. A los Centaleón les costará más detectar a su portador.",
        mejoras: "No tiene"
    },
    {
        id: 32,
        categoria: "cabeza",
        nombre: "Máscara de Kolog",
        icono: "img/iconos/mascara-kolog.png",
        imagen: "img/mascara-kolog.png",
        defensa: 1,
        efecto: "Alerta de la presencia de Kolog",
        bonificacion: "Ninguno",
        obtencion: "En el Bosque Perdido. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Máscara inspirada en las que llevan los Kolog. Vibra y emite sonidos cuando alguno de ellos se encuentra cerca. Es muy singular y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 33,
        categoria: "cabeza",
        nombre: "Máscara de la Deidad",
        icono: "img/iconos/mascara-deidad.png",
        imagen: "img/mascara-deidad.png",
        defensa: 3,
        efecto: "Ataque +",
        bonificacion: "Ataque cargado +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "La máscara que una vez llevó el héroe de un mundo amenazado de ser destruido por la luna. Da un poco de miedo, pero otorga un poder increíble a quien la porta.",
        mejoras: ["Uña de Hinox (x5) y Escama de Elden (x1) - Defensa: 5", "Colmillo de Hinox (x5) y Garra de Elden (x1) - Defensa: 8", "Víscera de Hinox (x5) y Colmillo de Elden (x1) Defensa: 12", "Víscera de Centaleón (x5) y Cuerno de Elden (x1) - Defensa: 20"]
    },
    {
        id: 34,
        categoria: "cabeza",
        nombre: "Máscara de Lizalfos",
        icono: "img/iconos/mascara-lizalfo.png",
        imagen: "img/mascara-lizalfo.png",
        defensa: 3,
        efecto: "Incógnito con Lizalfos",
        bonificacion: "Ninguno",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Máscara hecha a mano por Kilton. Incluye muchos detalles, como la lengua de reptil y el cuerno en espiral. Los lizalfos tardan más a detectar a su portador.",
        mejoras: "No tiene"
    },
    {
        id: 35,
        categoria: "cabeza",
        nombre: "Máscara de Majora",
        icono: "img/iconos/mascara-majora.png",
        imagen: "img/mascara-majora.png",
        defensa: 1,
        efecto: "Incógnito con enemigos",
        bonificacion: "Ninguno",
        obtencion: "Al sur del Lago Komolo, en el Cuartel de Komolo",
        descripcion: "Inquietante máscara heredada desde tiempos remotos que te ayuda a pasar desapercibido ante los enemigos. Es muy singular y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 36,
        categoria: "cabeza",
        nombre: "Máscara de Moblin",
        icono: "img/iconos/mascara-moblin.png",
        imagen: "img/mascara-moblin.png",
        defensa: 3,
        efecto: "Incógnito con Moblin",
        bonificacion: "Ninguno",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Una máscara hecha a mano por Kilton. El hocico alargado y el cuerno están muy bien logrados. Los Moblin tardan más en detectar a su portador.",
        mejoras: "No tiene"
    },
    {
        id: 37,
        categoria: "cabeza",
        nombre: "Máscara Oscura",
        icono: "img/iconos/mascara-oscura.png",
        imagen: "img/mascara-oscura.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Velocidad + durante la noche",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Una de las creaciones de Kilton. Quería representar a un monstruo nacido de las tinieblas. Los ojos rojos brillan día y noche con una luz espeluznante.",
        mejoras: "No tiene"
    },
    {
        id: 38,
        categoria: "cabeza",
        nombre: "Máscara de Sheik",
        icono: "img/iconos/mascara-sheik.png",
        imagen: "img/mascara-sheik.png",
        defensa: 2,
        efecto: "Sigilo +",
        bonificacion: "Ninguno",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Una máscara que se dice usó un Sheikah que salvó al héroe que viajaba en el tiempo. Confeccionado con los mejores tejidos de sigilo de Sheikah, es la última palabra en ropa de incógnito.",
        mejoras: ["Princesa de la calma (x1) y Fragmento de estrella (x1) - Defensa: 4", "Princesa de la calma (x2) y Fragmento de estrella (x2) - Defensa: 6", "Princesa de la calma (x3) y Fragmento de estrella (x3) - Defensa: 9", "Princesa de la calma (x4) y Fragmento de estrella (x4) - Defensa: 16"]
    },
    {
        id: 39,
        categoria: "cabeza",
        nombre: "Máscara de Sigilo",
        icono: "img/iconos/mascara-sigilo.png",
        imagen: "img/mascara-sigilo.png",
        defensa: 2,
        efecto: "Sigilo +",
        bonificacion: "Velocidad + durante la noche",
        obtencion: "En la tienda 'Moda al cuadrado' de la Aldea Kakariko",
        descripcion: "Máscara normal a simple vista, pero que camufla el sonido del cuerpo al moverse gracias a la tecnología Sheikah. Perfecta para pasar desapercibido.",
        mejoras: ["Flor sigilosa (x3) - Defensa: 4", "Flor sigilosa (x5) y Luciérnaga sigilosa (x5) - Defensa: 6", "Seta sigilosa (x8) y Caracol sigiloso (x5) - Defensa: 9", "Trucha sigilosa (x10) y Princesa de la calma (x5) - Defensa: 16"]
    },
    {
        id: 40,
        categoria: "cabeza",
        nombre: "Máscara Luminosa",
        icono: "img/iconos/mascara-luminosa.png",
        imagen: "img/mascara-luminosa.png",
        defensa: 3,
        efecto: "Cebo para esqueléticos",
        bonificacion: "Incógnito, armas esqueléticas +",
        obtencion: "En la tienda Club Secreto Gerudo",
        descripcion: "Prenda original del Club Secreto Gerudo, pintada con un tinte fabricado a base de gemas luminosas. Su brillo característico le da un aire muy misterioso en la oscuridad.",
        mejoras: ["Gema luminosa (x5) y Víscera de Bokoblin (x3) - Defensa: 5", "Gema luminosa (x8) y Víscera de Moblin (x3) - Defensa: 8", "Gema luminosa (x10) y Víscera de Moldora (x3) - Defensa: 12", "Gema luminosa (x20) y Víscera de Centaleón (x3) - Defensa: 20"]
    },
    {
        id: 41,
        categoria: "cabeza",
        nombre: "Pañuelo de Escalada",
        icono: "img/iconos/panuelo-escalada.png",
        imagen: "img/panuelo-escalada.png",
        defensa: 3,
        efecto: "Escalar +",
        bonificacion: "Resistencia escalada +",
        obtencion: "En el santuario de Ree Dahee",
        descripcion: "Pañuelo normal a simple vista, pero mejora notablemente el equilibrio de su portador gracias a tecnología ancestral. Se trata de un accesorio perfecto para escalar.",
        mejoras: ["Ala de keese (x3) y Seta de Hyrule (x3) - Defensa: 5", "Ala de Keese eléctrico (x5) y Lagarto raudo (x5) - Defensa: 8", "Ala de keese de hielo (x5) y Rana rauda (x10) - Defensa: 12", "Ala de keese de fuego (x5) y Violeta rauda (x15) - Defensa: 20"]
    },
    {
        id: 42,
        categoria: "cabeza",
        nombre: "Pendientes de Ámbar",
        icono: "img/iconos/pendientes-ambar.png",
        imagen: "img/pendientes-ambar.png",
        defensa: 4,
        efecto: "Resistencia al calor",
        bonificacion: "Ninguno",
        obtencion: "En la tienda 'La Gema del Desierto'",
        descripcion: "Pendientes de orfebrería gerudo elaborados con ámbar, un material que alberga el poder de la tierra. Aumentan la defensa de quien los lleva equipados.",
        mejoras: ["Ámbar (x5) y Pedernal (x3) - Defensa: 7", "Ámbar (x10) y Pedernal (x3) - Defensa: 12", "Ámbar (x20) y Pedernal (x3) - Defensa: 18", "Ámbar (x30) y Pedernal (x3) - Defensa: 28"]
    },
    {
        id: 43,
        categoria: "cabeza",
        nombre: "Pendientes de Ópalo",
        icono: "img/iconos/pendientes-opalo.png",
        imagen: "img/pendientes-opalo.png",
        defensa: 3,
        efecto: "Nadar +",
        bonificacion: "Ninguno",
        obtencion: "En la tienda 'La Gema del Desierto'",
        descripcion: "Accesorio gerudo adornado con ópalo, que posee poderes acuáticos. Gracias a la protección de la gema, la velocidad al nadar aumenta considerablemente.",
        mejoras: ["Ópalo (x5) y Pedernal (x3) - Defensa: 5", "Ópalo (x8) y Pedernal (x3) - Defensa: 8", "Ópalo (x16) y Pedernal (x3) - Defensa: 12", "Ópalo (x20) y Pedernal (x3) - Defensa: 20"]
    },
    {
        id: 44,
        categoria: "cabeza",
        nombre: "Pendientes de Topacio",
        icono: "img/iconos/pendientes-topacio.png",
        imagen: "img/pendientes-topacio.png",
        defensa: 3,
        efecto: "Resistencia a la electricidad",
        bonificacion: "Ninguno",
        obtencion: "En la tienda 'La Gema del Desierto'",
        descripcion: "Accesorio gerudo adornado con topacio, que posee poderes eléctricos. Gracias a la protección de la gema, se obtiene resistencia a la electricidad.",
        mejoras: ["Pedernal (x3) y Topacio (x2) - Defensa: 5", "Pedernal (x3) y Topacio (x4) - Defensa: 8", "Fragmento de estrella (x1) y Topacio (x6) - Defensa: 12", "Fragmento de estrella (x1) y Topacio (x10) - Defensa: 20"]
    },
    {
        id: 45,
        categoria: "cabeza",
        nombre: "Plumas Orni",
        icono: "img/iconos/plumas-orni.png",
        imagen: "img/plumas-orni.png",
        defensa: 3,
        efecto: "Resistencia al frío",
        bonificacion: "Anticongelación",
        obtencion: "En la tienda 'La Gema del Desierto'",
        descripcion: "Accesorio orni elaborado con plumas de pájaro de las nieves y que ayuda a resistir el frío. Se dice que el rubí que lo adorna alberga el poder del fuego.",
        mejoras: ["Gelatina ígnea (x3) - Defensa: 5", "Gelatina ígnea (x5) y Hierba ígnea (x3) - Defensa: 12", "Ala de keese de fuego (x8) y Seta ígnea (x5) - Defensa: 12", "Cola de lizalfos ígneo (x10) y Rubí (x5) - Defensa: 20"]
    },
    {
        id: 46,
        categoria: "cabeza",
        nombre: "Velo gerudo",
        icono: "img/iconos/velo-gerudo.png",
        imagen: "img/velo-gerudo.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Resistencia al calor",
        obtencion: "En el Bazar Sekken. Misión principal 'Misión de infiltración'",
        descripcion: "Máscara que utilizan las gerudo para protegerse del sol del desierto, pero que no guarda frente a ataques.",
        mejoras: "No tiene"
    },




    {
        id: 47,
        categoria: "armaduras",
        nombre: "Armadura Ancestral",
        icono: "img/iconos/armadura-ancestral.png",
        imagen: "img/set-ancestral.png",
        defensa: 4,
        efecto: "Resistencia ancestral",
        bonificacion: "Ataque ancestral +",
        obtencion: "En el laboratorio de Akkala",
        descripcion: "Armadura forjada mediante tecnología sheikah ancestral empleando partes de guardianes. Reduce el daño inflingido por armas ancestrales.",
        mejoras: ["Tornillo ancestral (x5) y Resorte ancestral (x5) - Defensa: 7", "Resorte ancestral (x15) y Engranaje ancestral (x10) - Defensa: 12", "Eje ancestral (x5) y Núcleo ancestral (x5) - Defensa: 18", "Fragmento de estrella (x3) y Gran núcleo ancestral (x3) - Defensa: 28"]

    }, {
        id: 48,
        categoria: "armaduras",
        nombre: "Armadura de Espectro",
        icono: "img/iconos/armadura-espectro.png",
        imagen: "img/set-espectro.png",
        defensa: 8,
        efecto: "Ataque +",
        bonificacion: "Ninguno",
        obtencion: "En las cercanías del cuartel de Hyrule. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Armadura idéntica a la que solían llevar los espectros blindados que, según la leyenda, aterrorizaban hasta al más valiente. Es muy preciada y difícil de conseguir.",
        mejoras: "No tiene"

    }, {
        id: 49,
        categoria: "armaduras",
        nombre: "Armadura Hyliana",
        icono: "img/iconos/armadura-hyliana.png",
        imagen: "img/set-soldado-hyliano.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En la tienda de aldea Hatelia",
        descripcion: "Armadura compuesta de robustas piezas metálicas, y predilecta de los guardias de Hyrule por su alto nivel defensivo. Su elaborada artesanía salta a la vista.",
        mejoras: ["Gelatina de chuchu (x5) y Víscera de bokoblin (x3) - Defensa: 7", "Ala de Keese (x5) y Víscera de Moblin (x3) - Defensa: 12", "Cola de Lizalfos (x5) y Víscera de Hinox (x3) - Defensa: 18", "Pezuña de Centaleón (x4) y Víscera de Centaleón (x2) - Defensa: 28"]

    }, {
        id: 50,
        categoria: "armaduras",
        nombre: "Armadura Ignífuga",
        icono: "img/iconos/armadura-ignifuga.png",
        imagen: "img/set-ignifugo.png",
        defensa: 3,
        efecto: "Resistencia al fuego",
        bonificacion: "Antillamas",
        obtencion: "En la tienda 'Magmanífico' de la Ciudad Goron.",
        descripcion: "Armadura fabricada especialmente para quienes se aventuren hasta Ciudad Goron. Al estar elaborada a base de piedras, ofrece resistencia al fuego.",
        mejoras: ["Lagarto ignífugo (x1) y Cuerno de moblin (x2) - Defensa: 5", "Lagarto ignífugo (x3) y Colmillo de Moblin (x4) - Defensa: 8", "Mariposa ignífuga (x3) y Víscera de moblin (x3) - Defensa: 12", "Mariposa ignífuga (x5) y Víscera de Hinox (x2) - Defensa: 20"]

    }, {
        id: 51,
        categoria: "armaduras",
        nombre: "Armadura Zora",
        icono: "img/iconos/armadura-zora.png",
        imagen: "img/set-zora.png",
        defensa: 3,
        efecto: "Nadar +, Poder ascender cascadas",
        bonificacion: "Resistencia al nadar +",
        obtencion: "A manos del Rey Dorphan en la región de los Zora durante la misión principal Bestia Divina Vah Ruta.",
        descripcion: "Elaborada generación tras generación por las princesas zora para sus futuros esposos. Al vestirlas se puede ascender por cascadas.",
        mejoras: ["Cuerno de Lizalfo (x3) - Defensa: 5", "Garra de Lizalfo (x5) y Lubina de Hyrule (x1) - Defensa: 8", "Cola de Lizalfo (x5) y Lubina vivaz (x5) - Defensa: 18", "Cola de Lizalfos (x10 ) y Ópalo (x15) - Defensa: 20"]

    },

    {
        id: 52,
        categoria: "armaduras",
        nombre: "Armadura de la Deidad",
        icono: "img/iconos/armadura-deidad.png",
        imagen: "img/set-deidad.png",
        defensa: 3,
        efecto: "Ataque +",
        bonificacion: "Ataque cargado +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda que esta armadura perteneció una vez al héroe de un mundo en el que la luna amenazaba con caer. Cuando lo usas, sientes que un poder feroz y divino fluye a través de ti.",
        mejoras: ["Uña de Hinox (x5) y Escama de Nayen (x1) - Defensa: 5", "Colmillo de Hinox (x5) y Garra de Nayen (x1) Defensa: 8", "Víscera de Hinox (x5) y Colmillo de Nayen (x1) - Defensa: 12", "Víscera de Centaleón (x5) y Cuerno de Nayen (x1) - Defensa: 20"]
    },

    {
        id: 53,
        categoria: "torso",
        nombre: "Camiseta de Escalada",
        icono: "img/iconos/camiseta-escalada.png",
        imagen: "img/set-escalada.png",
        defensa: 3,
        efecto: "Escalar +",
        bonificacion: "Resistencia escalar +",
        obtencion: "En el Santuario de Chaas Qeta",
        descripcion: "Atuendo para trepar elaborado por medio de tecnología ancestral y cuyos guantes evitan que se resbale.",
        mejoras: ["Ala de Keese (x3) y Seta de Hyrule (x3) - Defensa: 5", "Ala de Keese eléctrico (x5) y Lagarto raudo (x5) - Defensa: 8", "Ala de Keese de hielo (x5) y Rana rauda (x10) - Defensa: 12", "Ala de Keese de fuego (x5) y Violeta rauda (x15) - Defensa: 20"]


    },
    {
        id: 54,
        categoria: "torso",
        nombre: "Camiseta de Langosta",
        icono: "img/iconos/camiseta-langosta.png",
        imagen: "img/camiseta-langosta.png",
        defensa: 1,
        efecto: "Resistencia al calor",
        bonificacion: "Ninguno",
        obtencion: "En el Santuario de Chaas Qeta",
        descripcion: "Cierto héroe del viento vestía esta camiseta en su isla natal. De él se cuenta que podía controlar el viento para viajar por el océano. Es una prenda difícil de conseguir.",
        mejoras: "No tiene"


    },
    {
        id: 55,
        categoria: "torso",
        nombre: "Camiseta de Tingle",
        icono: "img/iconos/camiseta-tingle.png",
        imagen: "img/set-tingle.png",
        defensa: 2,
        efecto: "Ninguno",
        bonificacion: "Velocidad nocturna +",
        obtencion: "En el Santuario de Chaas Qeta",
        descripcion: "Camiseta similar a la de un individuo que afirmaba ser la rencarnación de un hada. Kurulin. Es muy difícil de conseguir.",
        mejoras: "No tiene"

    },
    {
        id: 56,
        categoria: "torso",
        nombre: "Camiseta Luminosa",
        icono: "img/iconos/camiseta-luminosa.png",
        imagen: "img/set-luminosa.png",
        defensa: 3,
        efecto: "Cebo para esqueléticos",
        bonificacion: "Incógnito con esqueléticos, Armas esqueléticas +",
        obtencion: "En el 'Club Secreto Gerudo'",
        descripcion: "Prenda que se vende clandestinamente en el Club Secreto Gerudo. Contiene un tinte a base de gemas luminosas que revela un misterioso diseño en la oscuridad.",
        mejoras: ["Gema luminosa (x5) y Víscera de Bokoblin (x3) - Defensa: 5", "Gema luminosa (x8) y Víscera de Moblin (x3) - Defensa: 8", "Gema luminosa (x10) y Víscera de moldora (x2) - Defensa: 12", "Gema luminosa (x20) y Víscera de centaleón (x1) - Defensa: 20"]

    },
    {
        id: 57,
        categoria: "torso",
        nombre: "Camiseta Nintendo Switch",
        icono: "img/iconos/camiseta-nintendo-switch.png",
        imagen: "img/camiseta-nintendo-switch.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En el 'Club Secreto Gerudo'",
        descripcion: "Una enigmática camiseta adornada con un logotipo de lo más peculiar. Es muy singular y difícil de conseguir. (Bonificación por la compra del pase de expansión).",
        mejoras: "No tiene"
    },
    {
        id: 58,
        categoria: "torso",
        nombre: "Camiseta Vieja",
        icono: "img/iconos/camiseta-vieja.png",
        imagen: "img/set-viejo.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En el santuario de Asiph ubicado en la meseta de los albores. Se habilita con el pase de expansión",
        descripcion: "Una camiseta sencilla y vieja. Está un poco rota y te queda pequeña, pero aún se puede usar.",
        mejoras: "No tiene"

    },
    {
        id: 59,
        categoria: "torso",
        nombre: "Casaca Forrada",
        icono: "img/iconos/casaca-forrada.png",
        imagen: "img/casaca-forrada.png",
        defensa: 1,
        efecto: "Resistencia al frío +",
        bonificacion: "Ninguno",
        obtencion: "Un regalo del Anciano en el prólogo o en la tienda 'Los Cuatro Vientos'en la Aldea Hatelia",
        descripcion: "Prenda de abrigo apreciada entre los habitantes de la montaña. Se fabrica con una tela recia y se complementa con un par de guantes.",
        mejoras: "No tiene"

    },
    {
        id: 60,
        categoria: "torso",
        nombre: "Chaleco de Buceador",
        icono: "img/iconos/chaleco-buceador.png",
        imagen: "img/set-buceador.png",
        defensa: 5,
        efecto: "Nadar +",
        bonificacion: "Ninguno",
        obtencion: "En el Lago Calavera, más específicamente al santuario de Izukna. Se activara con la misión secundaria 'Xenoblade Chronicles 2'",
        descripcion: "[Colaboración con Xenoblade Chronicles 2] Prenda imprescindible para todo aquel que quiera buscar tesoros en el mar de nubes. Es muy preciada y difícil de conseguir.",
        mejoras: "No tiene"

    },
    {
        id: 61,
        categoria: "torso",
        nombre: "Cota de Ganon Fantasma",
        icono: "img/iconos/cota-ganon-fantasma.png",
        imagen: "img/set-ganon-fantasma.png",
        defensa: 4,
        efecto: "Sigilo +",
        bonificacion: "Armas esqueléticas +",
        obtencion: "En el puente de Sarjon que cruza el río Faroria. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Se cuenta que esta armadura fue empleada por una entidad maligna que el rey malvado creó a su propia semejanza. Es muy preciada y difícil de conseguir.",
        mejoras: "No tiene"

    },
    {
        id: 62,
        categoria: "torso",
        nombre: "Hombrera del Desierto",
        icono: "img/iconos/hombrera-desierto.png",
        imagen: "img/set-desierto.png",
        defensa: 3,
        efecto: "Resistencia al calor",
        bonificacion: "Antielectricidad",
        obtencion: "En la tienda 'Club Secreto Gerudo' en la Ciudadela Gerudo. Y en la tienda 'El toque de Kaenne' en la Aldea Arkadia ",
        descripcion: "Armadura masculina que se vende en el Club Secreto Gerudo. Protege del calor gracias a los zafiros que tiene incrustados.",
        mejoras: "No tiene"

    },
    {
        id: 63,
        categoria: "torso",
        nombre: "Pechera de Bárbaro",
        icono: "img/iconos/pechera-barbaro.png",
        imagen: "img/set-barbaro.png",
        defensa: 3,
        efecto: "Ataque +",
        bonificacion: "Ataque cargado +",
        obtencion: "En el santuario de Dila Maag",
        descripcion: "Atuendo de una tribu guerrera que habitó en Farone hace mucho tiempo. Su diseño especial aumenta la fiereza y el ataque del portador.",
        mejoras: ["Cuerno de centaleón (x1) - Defensa: 5", "Cuerno de centaleón (x3) y Pezuña de centaleón (x2) - Defensa: 8", "Pezuña de centaleón (x4) y Víscera de centaleón (x1) - Defensa: 12", "Víscera de centaleón (x2) y Cuerno de Elden (x1) - Defensa: 20"]

    },
    {
        id: 64,
        categoria: "torso",
        nombre: "Pechera Gerudo",
        icono: "img/iconos/pechera-gerudo.png",
        imagen: "img/set-gerudo.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Resistencia al calor",
        obtencion: "En el Bazar Sekken en el Desierto de Gerudo",
        descripcion: "Prenda tradicional de las mujeres gerudo. Su diseño holgado mantiene el calor a raya, característica que la hace muy popular entre las integrantes de la tribu.",
        mejoras: "No tiene"

    },
    {
        id: 65,
        categoria: "torso",
        nombre: "Túnica Aislante",
        icono: "img/iconos/tunica-aislante.png",
        imagen: "img/set-aislante.png",
        defensa: 3,
        efecto: "Resistencia eléctrica",
        bonificacion: "Antirrayos",
        obtencion: "En el santuario Toh Yahsa o el la Tienda de Grante en la Aldea Arkadia",
        descripcion: "Valiosa prenda resistente a la electricidad. Se ha fabricado con un material denominado 'caucho' que ya no existe a día de hoy.",
        mejoras: ["Gelatina eléctrica (x3) - Defensa: 5", "Fruta electro (x5) y Gelatina eléctrica (x5) - Defensa: 8", "Cola de lizalfos eléctrico (x5) y Seta electro (x5) - Defensa: 12", "Cola de lizalfos eléctrico (x10) y Topacio (x10) - Defensa: 20"]

    },
    {
        id: 66,
        categoria: "torso",
        nombre: "Túnica del Sigilo",
        icono: "img/iconos/tunica-sigilo.png",
        imagen: "img/set-sigilo.png",
        defensa: 2,
        efecto: "Sigilo +",
        bonificacion: "Velocidad + durante la noche",
        obtencion: "En la tienda 'Moda al cuadrado' de la Aldea Kakariko",
        descripcion: "Prenda heredada entre los sheikah durante generaciones. Su tejido minimiza el ruido al moverse, incluso si es rápidamente.",
        mejoras: ["Flor sigilosa (x3) - Defensa: 4", "Flor sigilosa (x5) y Luciérnaga sigilosa (x5) - Defensa: 6", "Seta sigilosa (x8) y Seta Caracol sigiloso (x5) - Defensa: 9", "Trucha sigilosa (x10) y Princesa de la calma (x5) - Defensa: 16"]

    },
    {
        id: 67,
        categoria: "torso",
        nombre: "Túnica del Elegido",
        icono: "img/iconos/tunica-elegido.png",
        imagen: "img/tunica-elegido.png",
        defensa: 5,
        efecto: "Ver puntos de salud de los enemigos",
        bonificacion: "Ninguno",
        obtencion: "Se obtiene a manos de Impa en la ciudad de Kakariko al recuperar el primer recuerdo de Link",
        descripcion: "En la antigua Hyrule, esta prenda sólo podía ser usada por alguien que haya ganado el respeto de la Familia Real de Hyrule. Equipándola revelará la vida restante del enemigo.",
        mejoras: ["Princesa de la calma (x3) - Defensa: 8", "Princesa de la calma (x3) y Cuerno de Faren (x2) - Defensa: 14", "Princesa de la calma (x3) y Cuerno de Nayen (x2) - Defensa: 22", "Princesa de la calma (x10) y Cuerno de Elden (x2) - Defensa: 32"]

    },
    {
        id: 68,
        categoria: "torso",
        nombre: "Túnica del Cielo",
        icono: "img/iconos/tunica-cielo.png",
        imagen: "img/set-cielo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda que esta armadura una vez la usó un héroe que apareció del cielo montado sobre un poderoso pájaro. Aparentemente fue presentado para celebrar la finalización de una ceremonia.",
        mejoras: ["Zafiro (x1) y Fragmento de estrella (x1) - Defensa: 5", "Zafiro (x3) y Fragmento de estrella (x1) - Defensa: 8", "Zafiro (x5) y Fragmento de estrella (x1) - Defensa: 12", "Zafiro (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 69,
        categoria: "torso",
        nombre: "Túnica del Crepúsculo",
        icono: "img/iconos/tunica-crepusculo.png",
        imagen: "img/set-crepusculo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Según la leyenda, era la túnica de un héroe que combatió los monstruos del Crepúsculo. Tiene pelos de lobo.",
        mejoras: ["Topacio (x1) y Fragmento de estrella (x1) - Defensa: 5", "Topacio (x3) y Fragmento de estrella (x1) - Defensa: 8", "Topacio (x5) y Fragmento de estrella (x1) - Defensa: 12", "Topacio (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 70,
        categoria: "torso",
        nombre: "Túnica del Héroe",
        icono: "img/iconos/tunica-heroe.png",
        imagen: "img/set-heroe.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda de que este era el atuendo predilecto del héroe de tiempos ancestrales. La sencillez de su diseño lo hace muy tradicional.",
        mejoras: ["Rubí (x1) y Fragmento de estrella (x1) - Defensa: 5", "Rubí (x3) y Fragmento de estrella (x1) - Defensa: 8", "Rubí (x5) y Fragmento de estrella (x1) - Defensa: 12", "Rubí (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 71,
        categoria: "torso",
        nombre: "Túnica del Tiempo",
        icono: "img/iconos/tunica-tiempo.png",
        imagen: "img/set-tiempo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Según la leyenda, esta vestimenta la portaba un héroe que viajaba por el tiempo. Es apta para niños y adultos.",
        mejoras: ["Ámbar (x1) y Fragmento de estrella (x1) - Defensa: 5", "Ámbar (x3) y Fragmento de estrella (x1) - Defensa: 8", "Ámbar (x5) y Fragmento de estrella (x1) - Defensa: 12", "Ámbar (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 72,
        categoria: "torso",
        nombre: "Túnica del Viento",
        icono: "img/iconos/tunica-viento.png",
        imagen: "img/set-viento.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Según la leyenda, era la vestimenta favorita de un héroe que surcaba los mares. Se dice que fue un regalo de su abuela.",
        mejoras: ["Ópalo (x1) y Fragmento de estrella (x1) - Defensa: 5", "Ópalo (x3) y Fragmento de estrella (x1) - Defensa: 8", "Ópalo (x5) y Fragmento de estrella (x1) - Defensa: 12", "Ópalo (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 73,
        categoria: "torso",
        nombre: "Túnica de lo Salvaje",
        icono: "img/iconos/tunica-salvaje.png",
        imagen: "img/set-salvaje.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "En la misión secundaria 'Un regalo para los monjes'",
        descripcion: "Esta vestimenta ha sido confeccionada expresamente para un héroe que viaja por tierras salvajes. Por extraño que parezca, es justo tu talla.",
        mejoras: ["Bellota (x10) y Escama de Faren (x2) - Defensa: 7", "Miel de vigor (x5) y Garra de Faren (x2) - Defensa: 12", "Escarabajo vigoroso (x5) y Colmillo de Faren (x2) - Defensa: 18", "Cuerno de Faren (x2) y Fragmento de estrella (x1) - Defensa: 28"]

    },
    {
        id: 74,
        categoria: "torso",
        nombre: "Túnica Hyliana",
        icono: "img/iconos/tunica-hyliana.png",
        imagen: "img/set-hyliano.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En la tienda 'Moda al cuadrado' de la Aldea Kakariko",
        descripcion: "Prenda común, popular en todo Hyrule y muy apreciada por viajeros. Su tejido resistente y ligero hace que resulte muy fácil moverse con ella puesta.",
        mejoras: ["Cuerno de Bokoblin (x5) - Defensa: 5", "Cuerno de Bokoblin (x8) y Colmillo de Bokoblin (x5) - Defensa: 8", "Cuerno de Bokoblin (x10) y Víscera de Bokoblin (x5) - Defensa: 12", "Víscera de bokoblin (x15) y Ámbar (x15) - Defensa: 20"]

    },
    {
        id: 75,
        categoria: "torso",
        nombre: "Túnica Orni",
        icono: "img/iconos/tunica-orni.png",
        imagen: "img/set-orni.png",
        defensa: 3,
        efecto: "Resistencia al frío",
        bonificacion: "Anticongelación",
        obtencion: "En la tienda de 'Altos vuelos' en el Poblado Orni",
        descripcion: "Prenda orni que conserva muy bien el calor gracias a sus diversas capas de plumas. Fabricada por los miembros de dicha tribu para hylianos que visitan Tabanta y Hebra.",
        mejoras: ["Gelatina ígnea (x3) - Defensa: 5", "Gelatina ígnea (x5) y Hierba ígnea (x3) - Defensa: 8", "Ala de Keese de fuego (x8) y Seta ígnea (x5) - Defensa: 12", "Cola de Lizalfo ígneo (x10) y Rubí (x5) - Defensa: 20"]

    },
    {
        id: 76,
        categoria: "torso",
        nombre: "Túnica Oscura",
        icono: "img/iconos/tunica-oscura.png",
        imagen: "img/set-oscuro.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Velocidad + durante la noche",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Kilton diseño esta prenda negro azabache a raíz de numerosos estudios de monstruos. Se trata de una réplica de la vestimenta que llevó cierto héroe legendario.",
        mejoras: "No tiene"

    },
    {
        id: 77,
        categoria: "torso",
        nombre: "Uniforme de la Guardia Real",
        icono: "img/iconos/uniforme-guardia-real.png",
        imagen: "img/set-guardia-real.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ataque cargado +",
        obtencion: "Se encuentra dentro del castillo de Hyrule",
        descripcion: "Lo empleaba la guardia real de Hyrule. Además de ser elegante, está fabricado con materiales ligeros y resulta muy cómodo de vestir. Es muy singular y difícil de conseguir.",
        mejoras: "No tiene"

    },
    {
        id: 78,
        categoria: "piernas",
        nombre: "Botas de Ganon Fantasma",
        icono: "img/iconos/botas-ganon-fantasma.png",
        imagen: "img/set-ganon-fantasma.png",
        defensa: 4,
        efecto: "Sigilo +",
        bonificacion: "Armas esqueléticas +",
        obtencion: "En la parte occidental del bosque Ribrea. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Se cuenta que las empleaba una entidad maligna que el rey malvado creó a su propia semejanza. Son muy preciadas y difíciles de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 79,
        categoria: "piernas",
        nombre: "Botas de la Guardia Real",
        icono: "img/iconos/botas-guardia-real.png",
        imagen: "img/set-guardia-real.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ataque cargado +",
        obtencion: "Se encuentra dentro del castillo de Hyrule",
        descripcion: "Forman parte del atuendo de la guardia real de Hyrule. Destacan tanto por su elegancia como por ser prácticas y cómodas de llevar. Son muy singulares y difíciles de conseguir.",
        mejoras: "No tiene"

    },
    {
        id: 80,
        categoria: "piernas",
        nombre: "Botas de Nieve",
        icono: "img/iconos/botas-nieve.png",
        imagen: "img/botas-nieve.png",
        defensa: 3,
        efecto: "Rapidez en nieve +",
        bonificacion: "Ninguno",
        obtencion: "En las cercanías de la ciudadela Gerudo",
        descripcion: "Valiosas botas que distribuyen de forma uniforme el peso de su portador y le permiten desplazarse a buen ritmo sobre la nieve.",
        mejoras: ["Lagarto raudo (x10) y Tentáculo de Octorok (x5) - Defensa: 5", "Globo de octorok (x5) y Zanahoria rauda (x10) - Defensa: 8", "Ojo de Octorok (x5) y Seta rauda (x15) - Defensa: 12", "Escama de Nayen (x2) y Violeta rauda (x15) - Defensa: 20"]
    },
    {
        id: 81,
        categoria: "piernas",
        nombre: "Botas del Desierto",
        icono: "img/iconos/botas-desierto.png",
        imagen: "img/botas-desierto.png",
        defensa: 3,
        efecto: "Rapidez en arena +",
        bonificacion: "Ninguno",
        obtencion: "En las cercanías de la ciudadela Gerudo",
        descripcion: "Valiosas botas empleadas por la tribu gerudo hace mucho tiempo. No se hunden en la arena, permitiendo andar y correr a buen ritmo sobre esta.",
        mejoras: ["Aleta de moldora (x5) y Lagarto raudo (x10) - Defensa: 5", "Aleta de Moldora (x10) y Zanahoria rauda (x10) - Defensa: 8", "Seta rauda (x15) y Víscera de Moldora (x2) - Defensa: 12", "Violeta rauda (x15) y Víscera de Moldora (x4) - Defensa: 20"]
    },
    {
        id: 82,
        categoria: "piernas",
        nombre: "Grebas Ancestrales",
        icono: "img/iconos/grebas-ancestrales.png",
        imagen: "img/set-ancestral.png",
        defensa: 4,
        efecto: "Resistencia ancestral",
        bonificacion: "Ataque ancestral +",
        obtencion: "En el Laboratorio de Akkala",
        descripcion: "Rotver diseñó estas grebas en el instituto de investigación utilizando la misma tecnología que se encuentra en los Guardianes. Reducen el daño del armamento antiguo.",
        mejoras: ["Resorte ancestral (x5) y Tornillo ancestral (x5) - Defensa: 7", "Engranaje ancestral (x10) y Resorte ancestral (x15) - Defensa: 12", "Eje ancestral (x15) y Núcleo ancestral (x5) - Defensa: 18", "Fragmento de estrella (x1) y Gran núcleo ancestral (x2) - Defensa: 28"]
    },
    {
        id: 83,
        categoria: "piernas",
        nombre: "Grebas de Espectro",
        icono: "img/iconos/grebas-espectro.png",
        imagen: "img/set-espectro.png",
        defensa: 8,
        efecto: "Ataque +",
        bonificacion: "Ninguno",
        obtencion: "Dentro del altar ceremonial, al sur de la Ciudadela de Hyrule. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Grebas idénticas a la que solían llevar los espectros blindados que, según la leyenda, aterrorizaban hasta al más valiente. Son muy preciadas y difíciles de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 84,
        categoria: "piernas",
        nombre: "Grebas del Desierto",
        icono: "img/iconos/grebas-desierto.png",
        imagen: "img/set-desierto.png",
        defensa: 3,
        efecto: "Resistencia al calor",
        bonificacion: "Antielectricidad",
        obtencion: "En 'Club Secreto Gerudo' en la Ciudadela Gerudo. En la tienda 'El toque de Kaenne' en la Aldea Arkadia ",
        descripcion: "Prenda masculina que se halla a la venta en el Club Secreto Gerudo. Protege del calor gracias a los zafiros que tiene incrustados, puesto que albergan el poder del hielo.",
        mejoras: ["Gelatina gélida (x3) - Defensa: 5", "Gelatina gélida (x5) y Ala de Keese de hielo (x3) - Defensa: 8", "Ala de Keese de hielo (x8) y Cola de Lizalfo gélido (x3) - Defensa: 12", "Cola de Lizalfo gélido (x10) y Zafiro (x5) - Defensa: 20"]
    },
    {
        id: 85,
        categoria: "piernas",
        nombre: "Grebas Hylianas",
        icono: "img/iconos/grebas-hylianas.png",
        imagen: "img/set-soldado-hyliano.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En la tienda 'Los cuatro vientos' en la Aldea Hatelia",
        descripcion: "Prenda compuesta de piezas metálicas, predilecta de los guardias de Hyrule por su alta capacidad defensiva. Se tarda un poco en acostumbrarse a ella debido a su peso.",
        mejoras: ["Gelatina de chuchu (x5) y Víscera de Bokoblin (x3) - Defensa: 7", "Ojo de Keese (x3) y Víscera de Moblin (x3) - Defensa: 12", "Cola de Lizalfo (x3) y Víscera de Hinox (x1) - Defensa: 18", "Pezuña de Centaleón (x4) y Víscera de Centaleón (x2) - Defensa: 28"]
    },
    {
        id: 86,
        categoria: "piernas",
        nombre: "Grebas Ignífugas",
        icono: "img/iconos/grebas-ignifugas.png",
        imagen: "img/set-ignifugo.png",
        defensa: 3,
        efecto: "Resistencia al fuego",
        bonificacion: "Antillamas",
        obtencion: "En la tienda 'Magmanífico' en la Ciudad Goron",
        descripcion: "Prenda fabricada especialmente para los hylianos que se aventuren a Ciudad Goron. Al estar elaborada a base de piedras, ofrece resistencia al fuego.",
        mejoras: ["Lagarto ignífugo (x1) y Cuerno de Moblin (x2) - Defensa: 5", "Lagarto ignífugo (x3) y Colmillo de Moblin (x4) - Defensa: 8", "Mariposa ignífuga (x3) y Víscera de Moblin (x3) - Defensa: 12", "Mariposa ignífuga (x5) y Víscera de Hinox (x2) - Defensa: 20"]
    },
    {
        id: 87,
        categoria: "piernas",
        nombre: "Grebas Zora",
        icono: "img/iconos/grebas-zora.png",
        imagen: "img/set-zora.png",
        defensa: 3,
        efecto: "Nadar +",
        bonificacion: "Resistencia al nadar +",
        obtencion: "En la  la misión secundaria 'En busca del Centaleón'",
        descripcion: "Prenda heredada entre los zora. Las escamas de dragón que supuestamente la componen permiten al portador nadar más rápido.",
        mejoras: ["Cuerno de Lizalfo (x3) - Defensa: 5", "Garra de Lizalfo (x5) y Lubina de Hyrule (x1) - Defensa: 8", "Cola de Lizalfo (x5) y Lubina vivaz (x5) - Defensa: 12", "Cola de Lizalfo (x10) y Ópalo (x15) - Defensa: 20"]
    },
    {
        id: 88,
        categoria: "piernas",
        nombre: "Malla de Escalada",
        icono: "img/iconos/malla-escalada.png",
        imagen: "img/set-escalada.png",
        defensa: 3,
        efecto: "Escalar +",
        bonificacion: "Resistencia escalada +",
        obtencion: "En el santuario de Taho O'ah",
        descripcion: "Prenda diseñada para trepar por muros y riscos, elaborada por medio de tecnología ancestral. Las zapatillas cuentan con una sujeción especial que evita resbalar.",
        mejoras: ["Ala de Keese (x3) y Seta de Hyrule (x3) - Defensa: 5", "Ala de Keese eléctrico (x5) y Lagarto raudo (x5) - Defensa: 8", "Ala de Keese de hielo (x5) y Rana rauda (x10) - Defensa: 12", "Ala de Keese de fuego (x5) y Violeta rauda (x15) - Defensa: 20"]
    },
    {
        id: 89,
        categoria: "piernas",
        nombre: "Malla de Sigilo",
        icono: "img/iconos/malla-sigilo.png",
        imagen: "img/set-sigilo.png",
        defensa: 2,
        efecto: "Sigilo +",
        bonificacion: "Velocidad nocturna +",
        obtencion: "En la tienda 'Moda al cuadrado' en la Aldea Kakariko",
        descripcion: "Prenda usada por los sheikah cuyo tejido, elaborado por medio de tecnología ancestral, minimiza el ruido al moverse.",
        mejoras: ["Flor sigilosa (x3) - Defensa: 4", "Flor sigilosa (x5) y Luciérnaga sigilosa (x5) - Defensa: 6", "Seta sigilosa (x8) y Caracol sigiloso (x5) - Defensa: 9", "Trucha sigilosa (x10) y Princesa de la calma (x5) - Defensa: 16"]
    },
    {
        id: 90,
        categoria: "piernas",
        nombre: "Malla de Tingle",
        icono: "img/iconos/malla-tingle.png",
        imagen: "img/set-tingle.png",
        defensa: 2,
        efecto: "Ninguno",
        bonificacion: "Velocidad nocturna +",
        obtencion: "En la Aldea Mabe. Instalando el  DLC 'Las Pruebas Legendarias'",
        descripcion: "Mallas similares a las de un individuo que afirmaba ser la rencarnación de un hada. Kurulin. Son muy difíciles de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 91,
        categoria: "piernas",
        nombre: "Malla Luminosa",
        icono: "img/iconos/malla-luminosa.png",
        imagen: "img/set-luminosa.png",
        defensa: 3,
        efecto: "Cebo para esqueléticos",
        bonificacion: "Incógnito con esqueléticos, armas esqueléticas +",
        obtencion: "En 'Club Secreto Gerudo' en la Ciudadela Gerudo",
        descripcion: "Prenda que se vende clandestinamente en el Club Secreto Gerudo. Contiene un tinte a base de gemas luminosas que revela un misterioso diseño en la oscuridad.",
        mejoras: ["Gema luminosa (x5) y Víscera de Bokoblin (x3) - Defensa: 5", "Gema luminosa (x8) y Víscera de Moblin (x3) - Defensa: 8", "Gema luminosa (x10) y Víscera de Moldora (x2) - Defensa: 12", "Gema luminosa (x20) y Víscera de Centaleón (x1) - Defensa: 20"]
    },
    {
        id: 92,
        categoria: "piernas",
        nombre: "Pantalón Aislante",
        icono: "img/iconos/pantalon-aislante.png",
        imagen: "img/set-aislante.png",
        defensa: 3,
        efecto: "Resistencia eléctrica",
        bonificacion: "Antirrayos",
        obtencion: "En el santuario Qukah Nata. En la tienda de Grante en la Aldea Arkadia",
        descripcion: "Valiosa prenda resistente a la electricidad. Se ha fabricado con un material denominado 'caucho' que ya no existe a día de hoy.",
        mejoras: ["Gelatina eléctrica (x3) - Defensa: 5", "Fruta electro (x5) y Gelatina eléctrica (x5) - Defensa: 8", "Cola de Lizalfo eléctrico (x5) y Seta electro (x5) - Defensa: 12", "Cola de Lizalfo eléctrico (x10) y Topacio (x10) - Defensa: 20"]
    },
    {
        id: 93,
        categoria: "piernas",
        nombre: "Pantalón de Bárbaro",
        icono: "img/iconos/pantalon-barbaro.png",
        imagen: "img/set-barbaro.png",
        defensa: 3,
        efecto: "Ataque +",
        bonificacion: "Ataque cargado +",
        obtencion: "En el santuario de Qazza Tokki.",
        descripcion: "Prenda de una tribu guerrera que habitó en Farone hace mucho tiempo. Su diseño especial aumenta la fiereza y el ataque del portador.",
        mejoras: ["Cuerno de Centaleón (x1) - Defensa: 5", "Cuerno de Centaleón (x3) y Pezuña de Centaleón (x2) - Defensa: 8", "Pezuña de Centaleón (x4) y Víscera de Centaleón (x1) - Defensa: 12", "Víscera de Centaleón (x2) y Cuerno de Elden (x1) - Defensa: 20"]
    },
    {
        id: 94,
        categoria: "piernas",
        nombre: "Pantalón de Buceador",
        icono: "img/iconos/pantalon-buceador.png",
        imagen: "img/set-buceador.png",
        defensa: 5,
        efecto: "Nadar +",
        bonificacion: "Ninguno",
        obtencion: "En la cima de la Cumbre de Hebra,  la misión secundaria 'Xenoblade Chronicles 2'",
        descripcion: "[Colaboración con Xenoblade Chronicles 2] Prenda imprescindible para todo aquel que quiera buscar tesoros en el mar de nubes. Es muy preciada y difícil de conseguir.",
        mejoras: "No tiene"
    },
    {
        id: 95,
        categoria: "piernas",
        nombre: "Pantalón del Cielo",
        icono: "img/iconos/pantalon-cielo.png",
        imagen: "img/set-cielo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "La leyenda dice que estos pantalones los usó una vez un héroe que apareció del cielo montado en un pájaro poderoso. Era el atuendo oficial de cierta orden de caballeros.",
        mejoras: ["Zafiro (x1) y Fragmento de estrella (x1) - Defensa: 5", "Zafiro (x3) y Fragmento de estrella (x1) - Defensa: 8", "Zafiro (x5) y Fragmento de estrella (x1) - Defensa: 12", "Zafiro (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 96,
        categoria: "piernas",
        nombre: "Pantalón del Crepúsculo",
        icono: "img/iconos/pantalon-crepusculo.png",
        imagen: "img/set-crepusculo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda que un héroe que luchó contra los monstruos del Crepúsculo portó esta prenda. Su interior tiene restos de pelaje de lobo.",
        mejoras: ["Topacio (x1) y Fragmento de estrella (x1) - Defensa: 5", "Topacio (x3) y Fragmento de estrella (x1) - Defensa: 8", "Topacio (x5) y Fragmento de estrella (x1) - Defensa: 12", "Topacio (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 97,
        categoria: "piernas",
        nombre: "Pantalón del Héroe",
        icono: "img/iconos/pantalon-heroe.png",
        imagen: "img/set-heroe.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Según la leyenda, esta inusual prenda era la predilecta de un héroe de tiempos remotos. Su diseño es austero y tradicional.",
        mejoras: ["Rubí (x1) y Fragmento de estrella (x1) - Defensa: 5", "Rubí (x3) y Fragmento de estrella (x1) - Defensa: 8", "Rubí (x5) y Fragmento de estrella (x1) - Defensa: 12", "Rubí (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 98,
        categoria: "piernas",
        nombre: "Pantalón del Tiempo",
        icono: "img/iconos/pantalon-tiempo.png",
        imagen: "img/set-tiempo.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda que un héroe que viajaba por el tiempo portó esta prenda confeccionada por habitantes del bosque.",
        mejoras: ["Ámbar (x1) y Fragmento de estrella (x1) - Defensa: 5", "Ámbar (x3) y Fragmento de estrella (x1) - Defensa: 8", "Ámbar (x5) y Fragmento de estrella (x1) - Defensa: 12", "Ámbar (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 99,
        categoria: "piernas",
        nombre: "Pantalón del Viento",
        icono: "img/iconos/pantalon-viento.png",
        imagen: "img/set-viento.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "Se desbloquea con el amiibo correspondiente",
        descripcion: "Cuenta la leyenda que esta era la prenda predilecta de un héroe que surcó los mares.",
        mejoras: ["Ópalo (x1) y Fragmento de estrella (x1) - Defensa: 5", "Ópalo (x3) y Fragmento de estrella (x1) - Defensa: 8", "Ópalo (x5) y Fragmento de estrella (x1) - Defensa: 12", "Ópalo (x10) y Fragmento de estrella (x1) - Defensa: 20"]

    },
    {
        id: 100,
        categoria: "piernas",
        nombre: "Pantalón de lo Salvaje",
        icono: "img/iconos/pantalon-salvaje.png",
        imagen: "img/set-salvaje.png",
        defensa: 4,
        efecto: "Ninguno",
        bonificacion: "Rayo Espada Maestra +",
        obtencion: "En la misión secundaria 'Un regalo para los monjes'",
        descripcion: "Las leyendas dicen que estos pantalones fueron confeccionados para un héroe que viaja por tierras salvajes. Por extraño que parezca, son los pantalones más cómodos que jamás hayas usado.",
        mejoras: ["Bellota (x10) y Escama de Faren (x2) - Defensa: 7", "Miel de vigor (x5) y Garra de Faren (x2) - Defensa: 12", "Escarabajo vigoroso (x5) y Colmillo de Faren (x2) - Defensa: 18", "Cuerno de Faren (x2) y Fragmento de estrella (x1) - Defensa: 28"]
    },
    {
        id: 101,
        categoria: "piernas",
        nombre: "Pantalón Gerudo",
        icono: "img/iconos/pantalon-gerudo.png",
        imagen: "img/set-gerudo.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Resistencia al calor",
        obtencion: "En el Bazar Sekken en el Desierto de Gerudo",
        descripcion: "Prenda tradicional de la tribu gerudo. Su talle corto facilita el movimiento, mientras que su diseño sutil es muy valorado.",
        mejoras: "No tiene"
    },
    {
        id: 102,
        categoria: "piernas",
        nombre: "Pantalón Hyliano",
        icono: "img/iconos/pantalon-hyliano.png",
        imagen: "img/set-hyliano.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En las cercanías del Templo del Tiempo. En la tienda 'Moda al cuadrado' en la Aldea Kakariko",
        descripcion: "Prenda tradicional en todo Hyrule. Gracias a su tejido, resistente a la par que suave, resulta bastante cómoda, por lo que es muy apreciada entre los viajeros.",
        mejoras: ["Cuerno de Bokoblin (x5) - Defensa: 5", "Cuerno de Bokoblin (x8) y Colmillo de Bokoblin (x5) - Defensa: 8", "Cuerno de Bokoblin (x10) y Víscera de Bokoblin (x5) - Defensa: 12", "Víscera de Bokoblin (x15) y Ámbar (x15) - Defensa: 20"]
    },
    {
        id: 103,
        categoria: "piernas",
        nombre: "Pantalón Orni",
        icono: "img/iconos/pantalon-orni.png",
        imagen: "img/set-orni.png",
        defensa: 3,
        efecto: "Resistencia al frío",
        bonificacion: "Anticongelación",
        obtencion: "En la tienda Altos vuelos del Poblado Orni",
        descripcion: "Prenda forrada con plumas que mudan los orni y que los hylianos pueden comprar en el poblado orni. Conserva muy bien el calor.",
        mejoras: ["Gelatina ígnea (x3) - Defensa: 5", "Gelatina ígnea (x5) y Hierba ígnea (x3) - Defensa: 8", "Ala de Keese de fuego (x8) y Seta ígnea (x5) - Defensa: 12", "Cola de Lizalfo ígneo (x10) y Rubí (x5) - Defensa: 20"]
    },
    {
        id: 104,
        categoria: "piernas",
        nombre: "Pantalón Oscuro",
        icono: "img/iconos/pantalon-oscuro.png",
        imagen: "img/set-oscuro.png",
        defensa: 3,
        efecto: "Ninguno",
        bonificacion: "Velocidad + durante la noche",
        obtencion: "En la Monstruoteca de Kilton",
        descripcion: "Kilton diseño esta prenda negro azabache a raíz de numerosos estudios de monstruos. Parece normal, pero se confeccionó basada en un monstruo surgido de las tinieblas.",
        mejoras: "No tiene"
    },
    {
        id: 105,
        categoria: "piernas",
        nombre: "Pantalón Viejo",
        icono: "img/iconos/pantalon-viejo.png",
        imagen: "img/set-viejo.png",
        defensa: 1,
        efecto: "Ninguno",
        bonificacion: "Ninguno",
        obtencion: "En el santuario de la vida, una vez Link despierta de su letargo de cien años",
        descripcion: "Un pantalón viejo y desgastado por el tiempo. Todavía se puede usar, pero te queda un poco corto.",
        mejoras: "No tiene"
    },
];